In [6]:
import numpy as np
import time

In [13]:
size = 100_000_000 #10 million data set

py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"time for list: {end-start}")

np_array = np.array(py_list)
start = time.time()
sq_list = np_array ** 2
end = time.time()
print(f"np array time for list: {end-start}")


time for list: 4.439574956893921
np array time for list: 1.6061973571777344


In [18]:
# memory occupied
import sys

print(f"python list size: {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"np array size: {np_array.nbytes} bytes")

python list size: 80000005600000000 bytes
np array size: 800000000 bytes


In [25]:
# create - from list
arr = np.array([1,2,3,4])
print(arr, type(arr), arr.shape)

arr1 = np.array([1,2,3,4,"prime"])
print(arr1, type(arr1), arr1.shape)

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D, type(arr2D), arr2D.shape)

[1 2 3 4] <class 'numpy.ndarray'> (4,)
['1' '2' '3' '4' 'prime'] <class 'numpy.ndarray'> (5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3)


In [52]:
# in built methods
arr1 = np.zeros((2,3), dtype = "int64") #prefil with 0's
print(arr1, arr1.shape)

arr2 = np.ones((2,3)) #float 1.
print(arr2, arr2.shape)

arr3 = np.ones((2,3), dtype="int64") #float 1.
print(arr3, arr3.shape)

arr4 = np.full((3,4),100) #refill val
print(arr4, arr4.shape)

arr5 = np.eye((3), dtype="int64") #intendity matrix
print(arr5, arr5.shape)

arr6 = np.arange(0,11,2) #range elements (start, end, step)
print(arr6, arr6.shape)

arr7 = np.linspace(1, 100, 6) #evenly spaced arrays
print(arr7, arr7.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.   20.8  40.6  60.4  80.2 100. ] (6,)


In [60]:
# properties
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [66]:
# resahping array
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
reshape = arr.reshape((3,2))
print(reshape, reshape.shape)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [75]:
# fancy indexing
arr = np.array([1,2,3,4,5,6])

indexing = [0,1,3] #indexes
print(arr[indexing])

# boolean indexing

print(arr[arr > 2]) #val > 2
print(arr[arr % 2 == 0]) #even

[1 2 4]
[3 4 5 6]
[2 4 6]


In [77]:
# slicing
arr = np.array([1,2,3,4,5])

print(arr[1:4]) #[start, end, step]
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [96]:
# copy v/s view in slicing
raw_list = list(range(1,6))
print(f"raw list: {raw_list}")
sub_list = raw_list[1:4]
print(f"sub list: {sub_list}")
sub_list[0] = 100
print(f"sub list updated: {sub_list}")
print(f"raw list: {raw_list}")
print("*" * 50)
arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
sub_arr_copy = arr[1:3].copy() #if want to create a copy of an array
print(f"sub arr: {sub_arr}")
sub_arr[0] = 200 # in numpy changes will be done on arrays directly
print(f"sub arr updated: {sub_arr} ")
print(f"arr: {arr}")

raw list: [1, 2, 3, 4, 5]
sub list: [2, 3, 4]
sub list updated: [100, 3, 4]
raw list: [1, 2, 3, 4, 5]
**************************************************
sub arr: [2 3]
sub arr updated: [200   3] 
arr: [  1 200   3   4   5]
